### ISSUE TITLE
URL Report

### ISSUE THREAD

**Issue by jgamblin** [themains/virustotal#1]
Is there anyway to get this data in the R package as a data frame currently?
 
Command:
curl -v --request POST \
  --url 'https://www.virustotal.com/vtapi/v2/url/report' \
  -d apikey=$key\
  -d 'resource=http://www.virustotal.com/'

{"scan_id": "1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729", "resource": "http://www.virustotal.com/", "url": "http://www.virustotal.com/", "response_code": 1, "scan_date": "2017-04-18 18:22:09", "permalink": "https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/", "verbose_msg": "Scan finished, scan information embedded in this object", "filescan_id": null, "positives": 0, "total": 63, "scans": {"CLEAN MX": {"detected": false, "result": "clean site"}, "Rising": {"detected": false, "result": "clean site"}, "VX Vault": {"detected": false, "result": "clean site"}, "ZDB Zeus": {"detected": false, "result": "clean site"}, "Netcraft": {"detected": false, "result": "unrated site"}, "PhishLabs": {"detected": false, "result": "unrated site"}, "Zerofox": {"detected": false, "result": "clean site"}, "K7AntiVirus": {"detected": false, "result": "clean site"}, "SecureBrain": {"detected": false, "result": "clean site"}, "Quttera": {"detected": false, "result": "clean site"}, "AegisLab WebGuard": {"detected": false, "result": "clean site"}, "MalwareDomainList": {"detected": false, "result": "clean site", "detail": "http://www.malwaredomainlist.com/mdl.php?search=www.virustotal.com"}, "ZeusTracker": {"detected": false, "result": "clean site", "detail": "https://zeustracker.abuse.ch/monitor.php?host=www.virustotal.com"}, "zvelo": {"detected": false, "result": "clean site"}, "Google Safebrowsing": {"detected": false, "result": "clean site"}, "FraudScore": {"detected": false, "result": "clean site"}, "Kaspersky": {"detected": false, "result": "clean site"}, "BitDefender": {"detected": false, "result": "clean site"}, "Opera": {"detected": false, "result": "clean site"}, "Certly": {"detected": false, "result": "clean site"}, "ADMINUSLabs": {"detected": false, "result": "clean site"}, "CyberCrime": {"detected": false, "result": "clean site"}, "Websense ThreatSeeker": {"detected": false, "result": "clean site"}, "MalwarePatrol": {"detected": false, "result": "clean site"}, "Webutation": {"detected": false, "result": "clean site"}, "Trustwave": {"detected": false, "result": "clean site"}, "Web Security Guard": {"detected": false, "result": "clean site"}, "desenmascara.me": {"detected": false, "result": "clean site"}, "G-Data": {"detected": false, "result": "clean site"}, "Malwarebytes hpHosts": {"detected": false, "result": "clean site"}, "Dr.Web": {"detected": false, "result": "clean site"}, "AlienVault": {"detected": false, "result": "clean site"}, "Emsisoft": {"detected": false, "result": "clean site"}, "Malc0de Database": {"detected": false, "result": "clean site", "detail": "http://malc0de.com/database/index.php?search=www.virustotal.com"}, "malwares.com URL checker": {"detected": false, "result": "clean site"}, "Phishtank": {"detected": false, "result": "clean site"}, "Malwared": {"detected": false, "result": "clean site"}, "Avira": {"detected": false, "result": "clean site"}, "OpenPhish": {"detected": false, "result": "clean site"}, "Antiy-AVL": {"detected": false, "result": "clean site"}, "SCUMWARE.org": {"detected": false, "result": "clean site"}, "FraudSense": {"detected": false, "result": "clean site"}, "Comodo Site Inspector": {"detected": false, "result": "clean site"}, "Malekal": {"detected": false, "result": "clean site"}, "ESET": {"detected": false, "result": "clean site"}, "Sophos": {"detected": false, "result": "unrated site"}, "Yandex Safebrowsing": {"detected": false, "result": "clean site", "detail": "http://yandex.com/infected?l10n=en&url=http://www.virustotal.com/"}, "Spam404": {"detected": false, "result": "clean site"}, "Nucleon": {"detected": false, "result": "clean site"}, "Malware Domain Blocklist": {"detected": false, "result": "clean site"}, "Blueliv": {"detected": false, "result": "clean site"}, "ZCloudsec": {"detected": false, "result": "clean site"}, "AutoShun": {"detected": false, "result": "unrated site"}, "ThreatHive": {"detected": false, "result": "clean site"}, "ParetoLogic": {"detected": false, "result": "clean si* Curl_http_done: called premature == 0
* Connection #0 to host www.virustotal.com left intact
te"}, "Tencent": {"detected": false, "result": "clean site"}, "URLQuery": {"detected": false, "result": "unrated site"}, "StopBadware": {"detected": false, "result": "unrated site"}, "Sucuri SiteCheck": {"detected": false, "result": "clean site"}, "Fortinet": {"detected": false, "result": "clean site"}, "ZeroCERT": {"detected": false, "result": "clean site"}, "Baidu-International": {"detected": false, "result": "clean site"}, "securolytics": {"detected": false, "result": "clean site"}}

When I run this:
testvt <- url_report("www.virustotal.com", scan=0)

Output that doesnt return service: 
[testvt.txt](https://github.com/soodoku/virustotal/files/967815/testvt.txt)

The idea state would be a columns with the name of the service and the result.  Thanks for any help and let me know if you need more info.

**Comment by soodoku** [comment]
Dear @jgamblin, 

Thanks! I have fixed this. 

```
devtools::install_github("soodoku/virustotal")
testvt <- url_report("www.virustotal.com", scan=0)
head(testvt)
```
```
                                                                      scan_id           resource                        url response_code           scan_date
1 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
2 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
3 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
4 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
5 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
6 1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31-1492539729 www.virustotal.com http://www.virustotal.com/             1 2017-04-18 18:22:09
                                                                                                             permalink                                             verbose_msg positives total
1 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
2 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
3 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
4 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
5 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
6 https://www.virustotal.com/url/1db0ad7dbcec0676710ea0eaacd35d5e471d3e11944d53bcbd31f0cbd11bce31/analysis/1492539729/ Scan finished, scan information embedded in this object         0    63
        .id detected       result detail
1  CLEAN MX    FALSE   clean site   <NA>
2    Rising    FALSE   clean site   <NA>
3  VX Vault    FALSE   clean site   <NA>
4  ZDB Zeus    FALSE   clean site   <NA>
5  Netcraft    FALSE unrated site   <NA>
6 PhishLabs    FALSE unrated site   <NA>
```
